import {Dimensions, StyleSheet} from 'react-native';

export default StyleSheet.create({
  menuHeaderContain: {
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    backgroundColor: '#DA2328',
    paddingHorizontal: '2%',
    height: 90,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '95%',
    alignSelf: 'center',
  },
  imgLogo: {
    alignSelf: 'center',
    borderRadius: 10,
    width: 65,
    height: 80,
  },
  imageStyle: {
    padding: '3%',
    margin: '5%',
    tintColor: 'grey',
    height: 19,
    width: 19,
  },
  loginBtn: {
    width: '50%',
    height: 50,
    borderRadius: 30,
    backgroundColor: 'orange',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },

  containerr: {
    width: '75%',
    height: '50%',
    backgroundColor: '#ffffff',
    borderRadius: 33,
  },
  button: {
    height: 55,
    width: 55,
    backgroundColor: '#FED116',
    margin: 10,
    marginBottom: 20,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    width: '95%',
    padding: '4%',
    height: 55,
    marginBottom: 10,
    borderRadius: 30,
    borderWidth: 0.3,
    borderColor: 'grey',
    marginTop: 15,
  },
  sectionStylee: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    height: 65,
    padding: '3%',
    width: '90%',
    borderRadius: 30,
    borderWidth: 0.3,
    borderColor: 'grey',
  },

  input: {
    borderWidth: 0.3,
    width: 200,
    height: 35,
    borderRadius: 50,
    borderColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBtnBlue: {
    flexDirection: 'row',
    width: '10%',
    borderRadius: 12,
    width: '10%',
    height: 37,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {flex: 1, backgroundColor: '#1A1E21'},
  counterTxt: {
    fontWeight: '500',
    fontSize: 12,
    color: 'white',
    marginTop: '-27%',
  },
  searchTxt: {
    color: 'grey',
    fontWeight: '600',
    fontSize: 18,
  },
  TitleAndLogo: {
    backgroundColor: '#1A1E21',
    marginBottom: 14,
    marginTop: 30,
    paddingHorizontal: '3%',
    flexDirection: 'row',
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  title: {
    backgroundColor: '#1A1E21',
    justifyContent: 'center',
    marginLeft: -8,
    flexDirection: 'column',
  },

  titleTxt: {fontSize: 30, fontFamily: 'Rustler', color: 'white'},
  star: {
    width: 25,
    height: 25,
  },
  parent: {
    backgroundColor: '#1A1E21',
    width: Dimensions.get('window').width / 2,
  },
  subPraent: {
    marginBottom: '4%',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  productContainer: {
    borderRadius: 30,
    backgroundColor: '#2C2C2C',
    marginTop: '5%',
    width: '90%',
    height: 290,
  },
  lottie: {width: 90, height: 90},
  productImg: {
    borderRadius: 20,
    width: 160,
    marginBottom: 5,
    height: 110,
  },

  productTitle: {
    color: 'white',
    fontSize: 21,
    marginBottom: '7%',
    paddingHorizontal: '8%',
    fontFamily: 'RobotoSlab-Bold',
  },
  productType: {
    fontFamily: 'RobotoSlab-Bold',
    color: '#DA2328',
    fontSize: 15,
    paddingHorizontal: '8%',
  },
  productSub: {
    color: 'grey',
    fontSize: 17,
    paddingHorizontal: '8%',
    fontFamily: 'RobotoSlab-Bold',
  },
  productPrice: {
    paddingHorizontal: '8%',
    color: 'white',
    fontSize: 21,
    fontFamily: 'RobotoSlab-Bold',
  },

  cartBtnContainer: {
    bottom: 0,
    right: 0,
    position: 'absolute',
    borderRadius: 100,
    backgroundColor: '#1A1E21',
    height: 57,
    width: 57,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBtnSub: {
    flexDirection: null,
    borderRadius: 100,
    backgroundColor: '#DA2328',
    height: 45,
    width: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
